apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName }}
  namespace: {{.Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    environment: {{.Values.namespace }}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.appName }}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
        environment: {{.Values.namespace}}
    spec:
      containers:
        - name: {{.Values.appName}}
          image: {{.Values.image.registry}}/{{ .Values.image.name }}:{{ .Values.image.version }}
          ports:
            - containerPort: 8000
