name: docker-build-dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag site-traiteur-dev:$(date +%s)
    - name: Push the Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/site-traiteur-dev:latest
